[workspace]
members = [
    "bf_types",
    "bf_interp"
]

[package]
name = "brainfuck_interpreter"
version = "0.1.0"
edition = "2021"

[dependencies]
bf_types = { path = "./bf_types" }
bf_interp = { path = "./bf_interp" }